/* 
 * File:   main.cpp
 * Author: Venkatesh Tavva
 * Created on June 27, 2017, 4:35 PM
 * Purpose:  Calculate amount generated by selling different classes of seating at a stadium
 */

//System Libraries
#include <iostream>  //Input - Output Library
#include <iomanip>
using namespace std; //Name-space under which system libraries exist

//User Libraries

//Global Constants

//Function Prototypes

//Execution begins here
int main(int argc, char** argv) {
    //Declare variables
    double classA;
    double classB;
    double classC;
    double numberA;
    double numberB;
    double numberC;
    double total;
    
    //Initialize variables

    
    //Input data
    classA = 15;
    classB = 12;
    classC = 9;
    
    //Map inputs to outputs or process the data
    
    
    //Output the transformed data
    cout<<"Tickets sold for Class A:";
    cin>>numberA;
     cout<<"Tickets sold for Class B:";
    cin>>numberB;
     cout<<"Tickets sold for Class C:";
    cin>>numberC;
    cout<<setprecision(2)<<fixed<<showpoint;
    cout<< "Class A sales:$ "<<numberA *classA<<endl;
     cout<< "Class B sales:$ "<<numberB *classB<<endl;
      cout<< "Class C sales:$ "<<numberC *classC<<endl;
      total = (numberA*classA) + (numberB*classB) + (numberC*classC);
      cout<<"Total Sales $ "<<total<<endl;
    //Exit stage right!
    return 0;
}

